name: Build and deploy GH Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup git
      run: |
        git config user.email "build@cheeseburgers.com"
        git config user.name "GitHub Action"
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn install
    - run: yarn run build
    - run: yarn run release -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
