name: Build and Release GH Page

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup git
      run: |
        git config user.email "build@cheeseburgers.com"
        git config user.name "GitHub Action"
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn install
    - name: Test
      run: |
         yarn lint
         yarn test
    - name: Build
      env:
        REACT_APP_SCRAPE_API: 'https://vollerei.uc.r.appspot.com/scrape'
      run: |
        yarn build
        cp build/index.html build/404.html
    - name: Release
      if: ${{ github.ref == 'refs/heads/master' }}
      run: yarn release -xr https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
